### ISSUE TITLE
Allow override content-type to include types of charset

### ISSUE THREAD

**Issue by Michstumpf** [dclucas/routeBuilderDSL#13]
Today, this is fixed "application/json"
Allow set to "application/json; charset=utf-8"

**Comment by dclucas** [comment]
As per the JSON API specs:

> Clients MUST send all JSON API data in request documents with the header 
> Content-Type: application/vnd.api+json without any media type parameters.

Is there any other way to address your need without having to touch the content-type?

**Comment by dclucas** [comment]
This discussion, on another framework, raises some compelling case _against_ putting a charset in the content-type: https://github.com/request/request/issues/383

**Comment by dclucas** [comment]
Labeling as "won't fix" for now, but I can be convinced to change my mind ;)
