### ISSUE TITLE
DSL definition doesn't support properties type array

### ISSUE THREAD

**Issue by Michstumpf** [dclucas/routeBuilderDSL#3]
An error occurred while starting service spark.

Utilize this test definition: https://gist.github.com/Michstumpf/47e613b266a303d30c9c

![image](https://cloud.githubusercontent.com/assets/157079/7848708/9b7f0ece-04a4-11e5-9c56-74984c3f7ae9.png)

**Comment by dclucas** [comment]
Issue is fixed on the hotfix branch. Will take the opportunity to include another fix before releasing. In case of blockers, you can always pull from this branch ;)
