### ISSUE TITLE
All path contains same swagger definitions on the paths

### ISSUE THREAD

**Issue by Michstumpf** [dclucas/routeBuilderDSL#8]
All paths generated by swagger contains the document definitions of the first "Resource" loading in ResourceLoader.

This error cause a false schema validation.

Swagger doc returned
https://gist.github.com/Michstumpf/001415b57d18dbd01bfd

**Comment by dclucas** [comment]
Hm, do you have a resource with multiple definitions? Shouldn't you be declaring multiple resources, each with its own definition and paths?

**Comment by dclucas** [comment]
Hm, looks like this is really the case. In order not to try to do any magic, the system assumes that:
1. each resource declaration will be about only ONE resource
2. all paths reference the FIRST definition. That way, no magic is required.

Simplest solution on your case is to split the declaration of your resources in: multiple resources. As in:

```
def nfrResource = new Resource()
   .definitions
      ."NFe" { ... }
   .paths
      ."/nfe" { ... }

def nfrResource = new Resource()
   .definitions
      ."NFe" { ... }
   .paths
      ."/nfe" { ... }

def tmResource = new Resource()
   .definitions
      ."tipoMaquina" { ... }
   .paths
      ."/tipoMaquina" { ... }

def rl = new ResourceLoader()
rl.load(nfeResource)
rl.load(tmResource)
```
